import pygame

#Window dimentions
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 700

#Colors
BG_COLOR = (15, 6, 6)
PANEL_COLOR = (73, 0, 0)
ACCENT_COLOR = (32, 11, 11)
TEXT_COLOR = (255, 255, 255)
HIGHLIGHT_COLOR = (101, 0, 0)

#Routes
MUSIC_FOLDER = './music'
LYRICS_FOLDER = './lyrics'

#Layout divisions
SCREEN_AREA_WIDTH = 900
CONTROLS_AREA_WIDTH = 500
CONTROLS_AREA_X = 900

#Control circle
CIRCLE_CENTER_X = CONTROLS_AREA_X + 250
CIRCLE_CENTER_Y = WINDOW_HEIGHT // 2
CIRCLE_RADIUS = 150

#Button positions
BUTTON_SIZE = 50

#Button icon sizes
ICON_SIZE_CENTER = 18
ICON_SIZE_SIDE = 15

#Song info display
SONG_INFO_X = 20
SONG_TITLE_Y = 20
SONG_ARTIST_Y = 55

#Playlist display
PLAYLIST_TITLE_Y = 100
PLAYLIST_START_Y = 130
PLAYLIST_ITEM_HEIGHT = 40
PLAYLIST_ITEM_X = 40

#Lyrics display
LYRICS_LINE_SPACING = 80
LYRICS_CONTEXT_COLOR = (100, 100, 100)

#Font sizes
FONT_SIZE_BASE = 48 

FONT_SIZE_LYRICS_CURRENT = FONT_SIZE_BASE      
FONT_SIZE_LYRICS_CONTEXT = int(FONT_SIZE_BASE * 0.67)     
FONT_SIZE_TITLE = int(FONT_SIZE_BASE * 0.75)               
FONT_SIZE_ARTIST = int(FONT_SIZE_BASE * 0.58)               
FONT_SIZE_PLAYLIST_HEADER = int(FONT_SIZE_BASE * 0.67)      
FONT_SIZE_PLAYLIST_ITEM = int(FONT_SIZE_BASE * 0.67)       